---
grails:
    profile: plugin
    codegen:
        defaultPackage: grails.plugin.asyncmail
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    groovy:
        template:
            check-template-location: false

---
asynchronous:
    mail:
        override: false
        disable: false
        useFlushOnSave: true
        gparsPoolSize: 1
        newSessionOnImmediateSend: false
        default:
            attempt:
                interval: 300000       # Five minutes
            max:
                attempts:
                    count: 1
        send:
            immediately: true
            repeat:
                interval: 60000           # One minute
        expired:
            collector:
                repeat:
                    interval: 607000
        messages:
            at:
                once: 100
        clear:
            after:
                sent: false
        persistence:
            provider: hibernate      # Possible values are 'hibernate', 'hibernate4', 'mongodb'
---
dataSource:
    pooled: true
    jmxExport: true
    driverClassName: org.h2.Driver
    username: sa
    password:

environments:
    test:
        dataSource:
            dbCreate: update
            url: jdbc:h2:mem:testDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
